[theme]
primaryColor="#667eea"
backgroundColor="#f5f7fa"
secondaryBackgroundColor="#ffffff"
textColor="#2d3748"
font="sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
