services:
  # coqui:
  #   build:
  #     context: ../services/model-coqui
  #     dockerfile: Dockerfile
  #   image: mediatalk_coqui:latest
  #   environment:
  #     - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
  #   volumes:
  #     - ../models:/models
  #     - ../services/model-coqui:/app
  #   ports:
  #     - "5001:8000"

  # cosy:
  #   build:
  #     context: ../services/model-cosy
  #     dockerfile: Dockerfile
  #   image: mediatalk_cosy:latest
  #   ports:
  #     - "5002:8000"

  orpheus:
    build:
      context: ../services/modelOrpheus
      dockerfile: Dockerfile
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - ../models:/models
      - ../services/modelOrpheus:/app
      - ../outputs/orpheus:/tmp/orpheus_audio
    ports:
      - "5005:5005"

  meditron:
    build:
      context: ../services/modelMeditron
      dockerfile: Dockerfile
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - MEDITRON_MODEL=${MEDITRON_MODEL}
    volumes:
      - ../models:/models
      - ../services/modelMeditron:/app
    ports:
      - "5006:5006"
    depends_on:
      - orpheus
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 8G
    shm_size: 2gb

  whisper:
    build:
      context: ../services/modelWhisper
      dockerfile: Dockerfile
    environment:
      - WHISPER_MODEL=${WHISPER_MODEL:-tiny}
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
    volumes:
      - ../models:/models
      - ../services/modelWhisper:/app
    ports:
      - "5007:5007"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    shm_size: 1gb

  webui:
    build:
      context: ../services/webui
      dockerfile: Dockerfile
    volumes:
      - ../services/webui:/app
    ports:
      - "8080:8080"
    depends_on:
      - meditron
      - orpheus
      - whisper

  # csm:
  #   build:
  #     context: ../services/model-csm
  #     dockerfile: Dockerfile
  #   environment:
  #     - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
  #   volumes:
  #     - ../models:/models
  #     - ../services/model-csm:/app
  #   ports:
  #     - "5004:8000"

  # evaluator:
  #   build:
  #     context: ../evaluation
  #     dockerfile: ../docker/Dockerfile.base
  #   volumes:
  #     - ../models:/models
  #     - ../evaluation:/app
  #   depends_on:
  #     # - coqui
  #     # - cosy
  #     - orpheus
  #     - meditron
  #     # - csm